# Generated by Django 4.1 on 2022-08-23 15:54

# ckeditor removal
# import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consist", "0004_alter_consist_company"),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name="consist",
        #     name="notes",
        #     field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        # ),
    ]
