# Generated by Django 4.1.2 on 2022-11-27 00:10

from django.db import migrations, models
import ram.utils


class Migration(migrations.Migration):

    dependencies = [
        ("consist", "0006_md_to_html"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consist",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=ram.utils.DeduplicatedStorage,
                upload_to="images/",
            ),
        ),
    ]
