# Generated by Django 4.1.3 on 2023-01-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consist", "0007_alter_consist_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consist",
            options={"ordering": ["company", "-creation_time"]},
        ),
    ]
