# Generated by Django 5.0.4 on 2024-04-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consist", "0010_alter_consist_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consist",
            name="consist_address",
            field=models.SmallIntegerField(
                blank=True,
                default=None,
                help_text="DCC consist address if enabled",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="consist",
            name="era",
            field=models.CharField(
                blank=True, help_text="Era or epoch of the consist", max_length=32
            ),
        ),
    ]
