# Generated by Django 5.1.2 on 2024-11-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consist", "0011_alter_consist_consist_address_alter_consist_era"),
    ]

    operations = [
        migrations.AddField(
            model_name="consist",
            name="published",
            field=models.BooleanField(default=True),
        ),
    ]
