# Generated by Django 5.1.4 on 2025-01-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consist", "0013_consistitem_one_stock_per_consist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consistitem",
            name="order",
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
