# Generated by Django 5.1.4 on 2025-04-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consist", "0015_consist_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consistitem",
            name="order",
            field=models.PositiveIntegerField(),
        ),
    ]
