# Generated by Django 5.1.4 on 2025-05-02 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consist", "0017_consist_scale"),
        (
            "metadata",
            "0024_remove_genericdocument_tags_delete_decoderdocument_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="consist",
            name="scale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="metadata.scale"
            ),
        ),
    ]
