# Generated by Django 6.0 on 2026-01-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consist", "0018_alter_consist_scale"),
    ]

    operations = [
        migrations.AddField(
            model_name="consistitem",
            name="load",
            field=models.BooleanField(default=False),
        ),
    ]
