# Generated by Django 6.0.1 on 2026-01-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consist", "0019_consistitem_load"),
        (
            "metadata",
            "0027_company_company_slug_idx_company_company_country_idx_and_more",
        ),
        ("roster", "0041_rollingclass_roster_rc_company_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="consist",
            index=models.Index(fields=["published"], name="consist_published_idx"),
        ),
        migrations.AddIndex(
            model_name="consist",
            index=models.Index(fields=["scale"], name="consist_scale_idx"),
        ),
        migrations.AddIndex(
            model_name="consist",
            index=models.Index(fields=["company"], name="consist_company_idx"),
        ),
        migrations.AddIndex(
            model_name="consist",
            index=models.Index(
                fields=["published", "scale"], name="consist_pub_scale_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consistitem",
            index=models.Index(fields=["load"], name="consist_item_load_idx"),
        ),
        migrations.AddIndex(
            model_name="consistitem",
            index=models.Index(fields=["order"], name="consist_item_order_idx"),
        ),
        migrations.AddIndex(
            model_name="consistitem",
            index=models.Index(
                fields=["consist", "load"], name="consist_item_con_load_idx"
            ),
        ),
    ]
