# Generated by Django 4.0.3 on 2022-04-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rollingstockimage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rollingstockimage',
            name='is_thumbnail',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
