# Generated by Django 4.0.3 on 2022-04-12 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_alter_rollingstockimage_rolling_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollingstockdocument',
            name='rolling_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='roster.rollingstock'),
        ),
        migrations.AlterField(
            model_name='rollingstockimage',
            name='rolling_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='roster.rollingstock'),
        ),
    ]
