# Generated by Django 4.0.3 on 2022-04-12 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_alter_rollingstockdocument_rolling_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollingstockproperty',
            name='rolling_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='roster.rollingstock'),
        ),
    ]
