# Generated by Django 4.0.6 on 2022-07-13 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_alter_rollingstockproperty_rolling_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollingclassproperty',
            name='rolling_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='roster.rollingclass', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='rollingstock',
            name='rolling_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolling_class', to='roster.rollingclass', verbose_name='Class'),
        ),
    ]
