# Generated by Django 4.0.6 on 2022-08-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0009_alter_rollingstock_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollingstockdocument',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
