# Generated by Django 4.1 on 2022-08-23 15:54

# ckeditor removal
# import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0009_alter_rollingstock_options_and_more"),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name="rollingstock",
        #     name="notes",
        #     field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        # ),
    ]
