# Generated by Django 4.1 on 2022-08-27 12:43

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0011_md_to_html"),
    ]

    operations = [
        migrations.CreateModel(
            name="RollingStockJournal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("log", ckeditor_uploader.fields.RichTextUploadingField()),
                ("private", models.BooleanField(default=False)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "rolling_stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal",
                        to="roster.rollingstock",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "rolling_stock"],
            },
        ),
    ]
