# Generated by Django 4.1.2 on 2022-10-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0010_rollingstockdocument_private"),
        ("roster", "0012_rollingstockjournal"),
    ]

    operations = []
