# Generated by Django 4.1.3 on 2022-12-28 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0014_alter_rollingstockdocument_file_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rollingstockimage",
            options={"ordering": ["-is_thumbnail"]},
        ),
    ]
