# Generated by Django 4.1.3 on 2023-01-02 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0016_alter_rollingstockimage_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rollingstockimage",
            name="is_thumbnail",
        ),
    ]
