# Generated by Django 4.2.5 on 2023-10-01 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0017_remove_rollingstockimage_is_thumbnail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rollingstock",
            old_name="sku",
            new_name="item_number",
        ),
    ]
