# Generated by Django 4.2.5 on 2023-10-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0018_rename_sku_rollingstock_item_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="rollingstockdocument",
            name="private",
            field=models.BooleanField(default=False),
        ),
    ]
