# Generated by Django 4.2.6 on 2023-11-04 22:53

from django.db import migrations, models
import ram.utils
import roster.models


class Migration(migrations.Migration):
    dependencies = [
        ("roster", "0020_alter_rollingstockimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rollingstockdocument",
            name="file",
            field=models.FileField(
                storage=ram.utils.DeduplicatedStorage(), upload_to="files/"
            ),
        ),
        migrations.AlterField(
            model_name="rollingstockimage",
            name="image",
            field=models.ImageField(
                storage=ram.utils.DeduplicatedStorage,
                upload_to=roster.models.rolling_stock_image_upload,
            ),
        ),
    ]
