# Generated by Django 5.0.2 on 2024-02-17 12:19

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0021_alter_rollingstockdocument_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rollingstock",
            name="notes",
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name="rollingstockjournal",
            name="log",
            field=tinymce.models.HTMLField(),
        ),
    ]
