# Generated by Django 5.0.2 on 2024-03-02 13:30

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0022_alter_rollingstock_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rollingclass",
            name="description",
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
