# Generated by Django 5.0.2 on 2024-03-02 14:30

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0023_alter_rollingclass_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="rollingstock",
            name="description",
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
