# Generated by Django 5.0.4 on 2024-04-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0024_rollingstock_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="rollingstock",
            name="set",
            field=models.BooleanField(default=False, help_text="Part of a set"),
        ),
        migrations.AlterField(
            model_name="rollingstock",
            name="era",
            field=models.CharField(
                blank=True, help_text="Era or epoch of the model", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="rollingstock",
            name="item_number",
            field=models.CharField(
                blank=True, help_text="Catalog item number or code", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="rollingstockjournal",
            name="private",
            field=models.BooleanField(
                default=False,
                help_text="Journal log will be visible only to logged users",
            ),
        ),
    ]
