# Generated by Django 5.0.4 on 2024-04-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0026_rollingstock_item_number_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rollingstock",
            name="decoder_interface",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "Built-in"),
                    (1, "NEM651"),
                    (2, "NEM652"),
                    (3, "PluX"),
                    (4, "21MTC"),
                    (5, "Next18/Next18S"),
                ],
                null=True,
            ),
        ),
    ]
