# Generated by Django 5.1.2 on 2024-11-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0027_alter_rollingstock_decoder_interface"),
    ]

    operations = [
        migrations.AddField(
            model_name="rollingstock",
            name="published",
            field=models.BooleanField(default=True),
        ),
    ]
