# Generated by Django 5.1.2 on 2024-12-22 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0028_rollingstock_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rollingstockimage",
            options={"ordering": ["order"], "verbose_name_plural": "Images"},
        ),
    ]
