# Generated by Django 5.1.4 on 2025-01-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0030_rollingstock_price"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rollingstockdocument",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="rollingstockdocument",
            constraint=models.UniqueConstraint(
                fields=("rolling_stock", "file"), name="unique_stock_file"
            ),
        ),
    ]
