# Generated by Django 5.1.4 on 2025-01-18 11:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0031_alter_rollingstockdocument_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rollingstockdocument",
            name="creation_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rollingstockdocument",
            name="updated_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="rollingstockdocument",
            name="private",
            field=models.BooleanField(
                default=False, help_text="Document will be visible only to logged users"
            ),
        ),
    ]
