# Generated by Django 5.1.4 on 2025-01-27 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0023_shop"),
        ("roster", "0034_rollingstock_shop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rollingstock",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="metadata.shop",
            ),
        ),
    ]
