# Generated by Django 6.0 on 2025-12-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0038_alter_rollingstock_rolling_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="rollingstock",
            name="featured",
            field=models.BooleanField(
                default=False,
                help_text="Featured rolling stock will appear on the homepage",
            ),
        ),
    ]
