# Generated by Django 6.0 on 2025-12-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0038_alter_rollingstock_rolling_class"),
    ]

    operations = [
        migrations.CreateModel(
            name="RollingStockTelemetry",
            fields=[
                (
                    "bucket",
                    models.DateTimeField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("cab", models.PositiveIntegerField(editable=False)),
                ("avg_speed", models.FloatField(editable=False)),
                ("max_speed", models.PositiveIntegerField(editable=False)),
            ],
            options={
                "verbose_name_plural": "Telemetries",
                "db_table": "telemetry_10secs",
                "ordering": ["cab", "bucket"],
            },
        ),
    ]
