# Generated by Django 6.0 on 2026-01-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0039_rollingstock_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rollingstock",
            name="decoder_interface",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "Built-in"),
                    (1, "NEM651"),
                    (2, "NEM652"),
                    (3, "NEM658 (Plux22)"),
                    (4, "NEM660 (21MTC)"),
                    (5, "NEM662 (Next18/Next18S)"),
                    (3, "NEM658 (Plux16)"),
                ],
                null=True,
            ),
        ),
    ]
