# Generated by Django 6.0.1 on 2026-01-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "metadata",
            "0027_company_company_slug_idx_company_company_country_idx_and_more",
        ),
        ("roster", "0040_alter_rollingstock_decoder_interface_order"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="rollingclass",
            index=models.Index(fields=["company"], name="roster_rc_company_idx"),
        ),
        migrations.AddIndex(
            model_name="rollingclass",
            index=models.Index(fields=["type"], name="roster_rc_type_idx"),
        ),
        migrations.AddIndex(
            model_name="rollingclass",
            index=models.Index(
                fields=["company", "identifier"], name="roster_rc_co_ident_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rollingstock",
            index=models.Index(fields=["published"], name="roster_published_idx"),
        ),
        migrations.AddIndex(
            model_name="rollingstock",
            index=models.Index(fields=["featured"], name="roster_featured_idx"),
        ),
        migrations.AddIndex(
            model_name="rollingstock",
            index=models.Index(
                fields=["item_number_slug"], name="roster_item_slug_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rollingstock",
            index=models.Index(fields=["road_number_int"], name="roster_road_num_idx"),
        ),
        migrations.AddIndex(
            model_name="rollingstock",
            index=models.Index(
                fields=["published", "featured"], name="roster_pub_feat_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rollingstock",
            index=models.Index(
                fields=["manufacturer", "item_number_slug"], name="roster_mfr_item_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rollingstock",
            index=models.Index(fields=["scale"], name="roster_scale_idx"),
        ),
    ]
