# Generated by Django 4.0 on 2021-12-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoder',
            name='version',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
