# Generated by Django 4.0.2 on 2022-04-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.CharField(max_length=32, unique=True)),
                ('ratio', models.CharField(blank=True, max_length=16)),
                ('gauge', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='extended_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
