# Generated by Django 4.0.1 on 2022-01-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('metadata', '0003_company_logo_decoder_image_manufacturer_logo'), ('metadata', '0004_decoder_interface'), ('metadata', '0005_alter_decoder_interface'), ('metadata', '0006_alter_decoder_interface')]

    dependencies = [
        ('metadata', '0002_decoder_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='decoder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='decoder',
            name='interface',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'NEM651'), (2, 'NEM652'), (3, 'PluX'), (4, '21MTC'), (5, 'Next18/Next18S')], null=True),
        ),
    ]
