# Generated by Django 4.0.2 on 2022-04-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_scale_manufacturer_website_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='scale',
            options={'ordering': ['scale']},
        ),
        migrations.AlterField(
            model_name='rollingstocktype',
            name='category',
            field=models.CharField(choices=[('engine', 'Engine'), ('car', 'Car'), ('railcar', 'Railcar'), ('equipment', 'Equipment'), ('other', 'Other')], max_length=64),
        ),
    ]
