# Generated by Django 4.0.2 on 2022-04-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_alter_company_options_alter_scale_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='freelance',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='decoder',
            name='sound',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
