# Generated by Django 4.0.2 on 2022-03-06 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_tag_delete_equipment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
    ]
