# Generated by Django 4.0.3 on 2022-04-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_alter_company_freelance_alter_decoder_sound'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='category',
            field=models.CharField(choices=[('model', 'Model train'), ('real', 'Real train')], default='model', max_length=64),
            preserve_default=False,
        ),
    ]
