# Generated by Django 4.0.2 on 2022-03-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0006_alter_tag_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollingStockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
