# Generated by Django 4.0.2 on 2022-03-30 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_rollingstocktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rollingstocktype',
            name='type',
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('enginetype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='metadata.enginetype')),
            ],
            bases=('metadata.enginetype',),
        ),
        migrations.AddField(
            model_name='rollingstocktype',
            name='engine_type',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='engine_type', to='metadata.enginetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rollingstocktype',
            name='car_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='car_type', to='metadata.cartype'),
            preserve_default=False,
        ),
    ]
