# Generated by Django 4.0.3 on 2022-04-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_alter_manufacturer_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='category',
            field=models.CharField(choices=[('model', 'Model'), ('real', 'Real')], max_length=64),
        ),
    ]
