# Generated by Django 4.0.2 on 2022-03-30 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0008_enginetype_remove_rollingstocktype_type_cartype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='rollingstocktype',
            name='type',
            field=models.CharField(default='0', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rollingstocktype',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='metadata.typecategory'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='rollingstocktype',
            unique_together={('category', 'type')},
        ),
        migrations.RemoveField(
            model_name='rollingstocktype',
            name='car_type',
        ),
        migrations.RemoveField(
            model_name='rollingstocktype',
            name='engine_type',
        ),
        migrations.DeleteModel(
            name='CarType',
        ),
        migrations.DeleteModel(
            name='EngineType',
        ),
    ]
