# Generated by Django 4.0.2 on 2022-03-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0010_alter_typecategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollingstocktype',
            name='category',
            field=models.CharField(choices=[('engine', 'Engine'), ('car', 'Car')], max_length=64, unique=True),
        ),
        migrations.DeleteModel(
            name='TypeCategory',
        ),
    ]
