# Generated by Django 4.0.2 on 2022-03-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0011_alter_rollingstocktype_category_delete_typecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollingstocktype',
            name='category',
            field=models.CharField(choices=[('engine', 'Engine'), ('car', 'Car'), ('equipment', 'Equipment'), ('other', 'Other')], max_length=64),
        ),
    ]
