# Generated by Django 4.0.3 on 2022-04-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Map viewer', max_length=256)),
                ('site_author', models.CharField(blank=True, max_length=256)),
                ('about', models.TextField(blank=True)),
                ('maps_per_page', models.CharField(choices=[('6', '6'), ('9', '9'), ('12', '12'), ('15', '15'), ('18', '18'), ('21', '21'), ('24', '24'), ('27', '27'), ('30', '30')], default='6', max_length=2)),
                ('homepage_content', models.TextField(blank=True)),
                ('footer', models.TextField(blank=True)),
                ('footer_short', models.TextField(blank=True)),
                ('show_copyright', models.BooleanField(default=True)),
                ('show_version', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
