# Generated by Django 4.0.3 on 2022-04-09 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_siteconfiguration_site_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfiguration',
            old_name='maps_per_page',
            new_name='items_per_page',
        ),
    ]
