# Generated by Django 4.0.3 on 2022-04-09 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_rename_maps_per_page_siteconfiguration_items_per_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfiguration',
            old_name='footer_short',
            new_name='footer_extended',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='show_copyright',
        ),
    ]
