# Generated by Django 4.0.6 on 2022-07-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_siteconfiguration_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='items_ordering',
            field=models.CharField(choices=[('type', 'By rolling stock type'), ('company', 'By company name'), ('identifier', 'By rolling stock class')], default='type', max_length=10),
        ),
    ]
