# Generated by Django 4.0.6 on 2022-08-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_siteconfiguration_items_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flatpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('draft', models.BooleanField(default=True)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
