# Generated by Django 4.0.6 on 2022-08-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_flatpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='path',
            field=models.CharField(default='', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
