# Generated by Django 4.0.6 on 2022-08-07 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_flatpage_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flatpage',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
