# Generated by Django 4.1 on 2022-08-23 15:54

# ckeditor dependency removal
# import ckeditor.fields
# import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0010_flatpage_creation_time_flatpage_updated_time"),
    ]

    operations = [
#         migrations.AlterField(
#             model_name="flatpage",
#             name="content",
#             field=ckeditor_uploader.fields.RichTextUploadingField(),
#         ),
#         migrations.AlterField(
#             model_name="siteconfiguration",
#             name="about",
#             field=ckeditor.fields.RichTextField(blank=True),
#         ),
#         migrations.AlterField(
#             model_name="siteconfiguration",
#             name="footer",
#             field=ckeditor.fields.RichTextField(blank=True),
#         ),
#         migrations.AlterField(
#             model_name="siteconfiguration",
#             name="footer_extended",
#             field=ckeditor.fields.RichTextField(blank=True),
#         ),
    ]
