# Generated by Django 4.1.3 on 2022-12-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0013_remove_flatpage_draft_flatpage_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="extra_head",
            field=models.TextField(blank=True),
        ),
    ]
