# Generated by Django 4.1.5 on 2023-01-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0014_siteconfiguration_extra_head"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="use_cdn",
            field=models.BooleanField(default=True),
        ),
    ]
