# Generated by Django 5.0.1 on 2024-01-20 21:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0015_siteconfiguration_use_cdn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="site_name",
        ),
    ]
