# Generated by Django 5.0.2 on 2024-02-17 12:19

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0016_remove_siteconfiguration_site_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flatpage",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="about",
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="footer",
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="footer_extended",
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
