# Generated by Django 5.1.4 on 2025-01-30 16:39

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0018_siteconfiguration_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="disclaimer",
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
