# Generated by Django 5.1.4 on 2025-02-01 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0019_siteconfiguration_disclaimer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flatpage",
            options={"verbose_name": "page", "verbose_name_plural": "pages"},
        ),
    ]
