# Generated by Django 6.0 on 2026-01-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0020_alter_flatpage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="featured_items_ordering",
            field=models.CharField(
                choices=[
                    ("type", "By rolling stock type and company"),
                    ("class", "By rolling stock type and class"),
                    ("company", "By company and type"),
                    ("country", "By country and type"),
                    ("cou+com", "By country and company"),
                ],
                default="type",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="items_ordering",
            field=models.CharField(
                choices=[
                    ("type", "By rolling stock type and company"),
                    ("class", "By rolling stock type and class"),
                    ("company", "By company and type"),
                    ("country", "By country and type"),
                    ("cou+com", "By country and company"),
                ],
                default="type",
                max_length=11,
            ),
        ),
    ]
