# Generated by Django 6.0.1 on 2026-01-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0021_siteconfiguration_featured_items_ordering_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="siteconfiguration",
            old_name="extra_head",
            new_name="extra_html",
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="extra_html",
            field=models.TextField(
                blank=True,
                help_text="Extra HTML to be dinamically loaded into the site.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="extra_js",
            field=models.TextField(
                blank=True,
                help_text="Extra JS to be dinamically loaded into the site."
            ),
        ),
    ]
