# Generated by Django 4.2.5 on 2023-10-02 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0003_bookimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="numbers_of_pages",
            new_name="number_of_pages",
        ),
    ]
