# Generated by Django 4.2.5 on 2023-10-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0005_alter_book_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="ISBN",
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
