# Generated by Django 4.2.5 on 2023-10-03 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0006_alter_book_isbn"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["title"]},
        ),
    ]
