# Generated by Django 4.2.6 on 2023-10-09 21:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookshelf", "0007_alter_book_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AlterModelOptions(
            name="publisher",
            options={"ordering": ["name"]},
        ),
    ]
