# Generated by Django 5.0.2 on 2024-02-17 12:19

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0011_alter_book_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="notes",
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
