# Generated by Django 5.1.2 on 2024-11-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0013_book_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="published",
            field=models.BooleanField(default=True),
        ),
    ]
