# Generated by Django 5.1.2 on 2024-11-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0014_book_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(blank=True, to="bookshelf.author"),
        ),
    ]
