# Generated by Django 5.1.4 on 2024-12-22 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0017_alter_basebook_options_basebookdocument"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basebookdocument",
            options={"verbose_name_plural": "Documents"},
        ),
    ]
