# Generated by Django 5.1.4 on 2025-01-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0019_basebook_price"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="basebookdocument",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="basebookdocument",
            constraint=models.UniqueConstraint(
                fields=("book", "file"), name="unique_book_file"
            ),
        ),
    ]
