# Generated by Django 6.0 on 2025-12-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0026_alter_basebook_language_alter_magazine_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="magazine",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
