# Generated by Django 6.0 on 2025-12-21 21:56

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0027_magazine_website"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="magazine",
            options={"ordering": [django.db.models.functions.text.Lower("name")]},
        ),
        migrations.AlterModelOptions(
            name="magazineissue",
            options={
                "ordering": [
                    "magazine",
                    "publication_year",
                    "publication_month",
                    "issue_number",
                ]
            },
        ),
    ]
