# Generated by Django 6.0 on 2025-12-23 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0028_alter_magazine_options_alter_magazineissue_options"),
        ("metadata", "0025_alter_company_options_alter_manufacturer_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalog",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalogs",
                to="metadata.manufacturer",
            ),
        ),
        migrations.AlterField(
            model_name="catalog",
            name="scales",
            field=models.ManyToManyField(related_name="catalogs", to="metadata.scale"),
        ),
    ]
