# Generated by Django 6.0 on 2025-12-29 11:02

import django.db.models.deletion
import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0029_alter_catalog_manufacturer_alter_catalog_scales"),
    ]

    operations = [
        migrations.CreateModel(
            name="TocEntry",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", tinymce.models.HTMLField(blank=True)),
                ("notes", tinymce.models.HTMLField(blank=True)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("published", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=200)),
                ("authors", models.CharField(blank=True, max_length=256)),
                ("page", models.SmallIntegerField()),
                ("featured", models.BooleanField(default=False)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toc",
                        to="bookshelf.basebook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Table of Contents Entry",
                "verbose_name_plural": "Table of Contents Entries",
                "ordering": ["page"],
            },
        ),
    ]
