# Generated by Django 6.0 on 2025-12-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0030_tocentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tocentry",
            name="authors",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="tocentry",
            name="subtitle",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="tocentry",
            name="title",
            field=models.CharField(),
        ),
    ]
