# Generated by Django 6.0.1 on 2026-01-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0031_alter_tocentry_authors_alter_tocentry_subtitle_and_more"),
        (
            "metadata",
            "0027_company_company_slug_idx_company_company_country_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["title"], name="book_title_idx"),
        ),
        migrations.AddIndex(
            model_name="catalog",
            index=models.Index(fields=["manufacturer"], name="catalog_mfr_idx"),
        ),
        migrations.AddIndex(
            model_name="magazine",
            index=models.Index(fields=["published"], name="magazine_published_idx"),
        ),
        migrations.AddIndex(
            model_name="magazine",
            index=models.Index(fields=["name"], name="magazine_name_idx"),
        ),
        migrations.AddIndex(
            model_name="magazineissue",
            index=models.Index(fields=["magazine"], name="mag_issue_mag_idx"),
        ),
        migrations.AddIndex(
            model_name="magazineissue",
            index=models.Index(
                fields=["publication_month"], name="mag_issue_pub_month_idx"
            ),
        ),
    ]
