# Generated by Django 4.0.3 on 2022-04-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_driverconfiguration_network_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverconfiguration',
            name='network',
            field=models.GenericIPAddressField(blank=True, default='192.168.4.0', null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='driverconfiguration',
            name='remote_host',
            field=models.GenericIPAddressField(blank=True, default='192.168.4.1', null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='driverconfiguration',
            name='subnet_mask',
            field=models.GenericIPAddressField(blank=True, default='255.255.255.0', null=True, protocol='IPv4'),
        ),
    ]
