# Generated by Django 4.0.6 on 2022-07-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_alter_driverconfiguration_remote_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverconfiguration',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
