# Generated by Django 4.0.6 on 2022-07-10 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decoder',
            name='manufacturer',
            field=models.ForeignKey(limit_choices_to={'category': 'model'}, on_delete=django.db.models.deletion.CASCADE, to='metadata.manufacturer'),
        ),
    ]
