# Generated by Django 4.0.6 on 2022-07-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_alter_decoder_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
