# Generated by Django 4.0.6 on 2022-07-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_property_private'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rollingstocktype',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='rollingstocktype',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
