# Generated by Django 4.0.6 on 2022-07-18 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_alter_rollingstocktype_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scale',
            old_name='gauge',
            new_name='track',
        ),
    ]
