# Generated by Django 4.1.2 on 2022-11-27 00:10

from django.db import migrations, models
import ram.utils


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0008_remove_decoder_interface"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=ram.utils.DeduplicatedStorage,
                upload_to="images/",
            ),
        ),
        migrations.AlterField(
            model_name="decoder",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=ram.utils.DeduplicatedStorage,
                upload_to="images/",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=ram.utils.DeduplicatedStorage,
                upload_to="images/",
            ),
        ),
    ]
