# Generated by Django 4.1.5 on 2023-01-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0009_alter_company_logo_alter_decoder_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturer",
            name="category",
            field=models.CharField(
                choices=[
                    ("model", "Model"),
                    ("real", "Real"),
                    ("accessory", "Accessory"),
                    ("other", "Other"),
                ],
                max_length=64,
            ),
        ),
    ]
