# Generated by Django 4.2.5 on 2023-10-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0012_alter_decoder_manufacturer_decoderdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="decoderdocument",
            name="private",
            field=models.BooleanField(default=False),
        ),
    ]
