# Generated by Django 4.2.6 on 2023-10-10 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metadata", "0013_decoderdocument_private"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="decoder",
            options={"ordering": ["manufacturer", "name"]},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"]},
        ),
    ]
