# Generated by Django 5.1.2 on 2024-11-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0018_alter_decoder_options_alter_scale_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scale",
            name="gauge",
            field=models.CharField(
                blank=True,
                help_text="Distance between real tracks. Please specify the unit (mm, in, ...)",
                max_length=16,
            ),
        ),
    ]
