# Generated by Django 5.1.4 on 2025-01-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0019_alter_scale_gauge"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="decoderdocument",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="rollingstocktype",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="decoderdocument",
            constraint=models.UniqueConstraint(
                fields=("decoder", "file"), name="unique_decoder_file"
            ),
        ),
        migrations.AddConstraint(
            model_name="rollingstocktype",
            constraint=models.UniqueConstraint(
                fields=("category", "type"), name="unique_category_type"
            ),
        ),
    ]
