# Generated by Django 5.1.4 on 2025-01-18 11:20

import django.utils.timezone
import django_countries.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0021_genericdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="decoderdocument",
            name="creation_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="decoderdocument",
            name="updated_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="genericdocument",
            name="creation_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="genericdocument",
            name="notes",
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name="genericdocument",
            name="updated_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="country",
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="decoderdocument",
            name="private",
            field=models.BooleanField(
                default=False, help_text="Document will be visible only to logged users"
            ),
        ),
        migrations.AlterField(
            model_name="genericdocument",
            name="private",
            field=models.BooleanField(
                default=False, help_text="Document will be visible only to logged users"
            ),
        ),
    ]
