# Generated by Django 5.1.4 on 2025-02-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0023_shop"),
        ("repository", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genericdocument",
            name="tags",
        ),
        migrations.DeleteModel(
            name="DecoderDocument",
        ),
        migrations.DeleteModel(
            name="GenericDocument",
        ),
    ]
