# Generated by Django 5.1.4 on 2025-05-04 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "metadata",
            "0024_remove_genericdocument_tags_delete_decoderdocument_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ["slug"], "verbose_name_plural": "Companies"},
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={"ordering": ["category", "slug"]},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["slug"]},
        ),
    ]
