# Generated by Django 6.0 on 2026-01-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0025_alter_company_options_alter_manufacturer_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AddConstraint(
            model_name="manufacturer",
            constraint=models.UniqueConstraint(
                fields=("name", "category"), name="unique_name_category"
            ),
        ),
    ]
