# Generated by Django 6.0.1 on 2026-01-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0026_alter_manufacturer_name_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["slug"], name="company_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["country"], name="company_country_idx"),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["freelance"], name="company_freelance_idx"),
        ),
        migrations.AddIndex(
            model_name="manufacturer",
            index=models.Index(fields=["category"], name="mfr_category_idx"),
        ),
        migrations.AddIndex(
            model_name="manufacturer",
            index=models.Index(fields=["slug"], name="mfr_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="manufacturer",
            index=models.Index(fields=["category", "slug"], name="mfr_cat_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="scale",
            index=models.Index(fields=["slug"], name="scale_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="scale",
            index=models.Index(fields=["ratio_int"], name="scale_ratio_idx"),
        ),
        migrations.AddIndex(
            model_name="scale",
            index=models.Index(
                fields=["-ratio_int", "-tracks"], name="scale_ratio_tracks_idx"
            ),
        ),
    ]
