# Generated by Django 4.0.2 on 2022-04-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consistitem',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='consistitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
