# Generated by Django 4.0.2 on 2022-04-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consist',
            old_name='address',
            new_name='consist_address',
        ),
        migrations.RenameField(
            model_name='consist',
            old_name='epoch',
            new_name='era',
        ),
    ]
