# Generated by Django 4.0.3 on 2022-04-02 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consist', '0002_rename_address_consist_consist_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consistitem',
            name='consist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consist_item', to='consist.consist'),
        ),
    ]
