# Generated by Django 4.0.2 on 2022-04-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consist', '0002_alter_consistitem_options_consistitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='consist',
            name='address',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
