# Generated by Django 4.0 on 2022-01-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverconfiguration',
            options={'verbose_name': 'Configuration'},
        ),
        migrations.AddField(
            model_name='driverconfiguration',
            name='timeout',
            field=models.SmallIntegerField(default=250),
        ),
    ]
