# Generated by Django 5.1.4 on 2025-02-09 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0023_delete_basebookdocument"),
        (
            "metadata",
            "0024_remove_genericdocument_tags_delete_decoderdocument_and_more",
        ),
        ("repository", "0001_initial"),
        ("roster", "0036_delete_rollingstockdocument"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="decoderdocument",
            options={},
        ),
        migrations.AlterModelOptions(
            name="rollingstockdocument",
            options={},
        ),
        migrations.AlterField(
            model_name="basebookdocument",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document",
                to="bookshelf.basebook",
            ),
        ),
        migrations.AlterField(
            model_name="decoderdocument",
            name="decoder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document",
                to="metadata.decoder",
            ),
        ),
        migrations.AlterField(
            model_name="genericdocument",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="document", to="metadata.tag"
            ),
        ),
        migrations.AlterField(
            model_name="rollingstockdocument",
            name="rolling_stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document",
                to="roster.rollingstock",
            ),
        ),
        migrations.AddConstraint(
            model_name="basebookdocument",
            constraint=models.UniqueConstraint(
                fields=("book", "file"), name="unique_book_file"
            ),
        ),
        migrations.AddConstraint(
            model_name="decoderdocument",
            constraint=models.UniqueConstraint(
                fields=("decoder", "file"), name="unique_decoder_file"
            ),
        ),
        migrations.AddConstraint(
            model_name="rollingstockdocument",
            constraint=models.UniqueConstraint(
                fields=("rolling_stock", "file"), name="unique_stock_file"
            ),
        ),
    ]
