# Generated by Django 5.2.7 on 2025-10-28 21:17

import ram.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0002_invoicedocument_remove_basebookdocument_book_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookdocument",
            name="file",
            field=models.FileField(
                storage=ram.utils.DeduplicatedStorage, upload_to="files/"
            ),
        ),
        migrations.AlterField(
            model_name="catalogdocument",
            name="file",
            field=models.FileField(
                storage=ram.utils.DeduplicatedStorage, upload_to="files/"
            ),
        ),
        migrations.AlterField(
            model_name="decoderdocument",
            name="file",
            field=models.FileField(
                storage=ram.utils.DeduplicatedStorage, upload_to="files/"
            ),
        ),
        migrations.AlterField(
            model_name="genericdocument",
            name="file",
            field=models.FileField(
                storage=ram.utils.DeduplicatedStorage, upload_to="files/"
            ),
        ),
        migrations.AlterField(
            model_name="rollingstockdocument",
            name="file",
            field=models.FileField(
                storage=ram.utils.DeduplicatedStorage, upload_to="files/"
            ),
        ),
    ]
