# Generated by Django 5.1.4 on 2025-02-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0023_delete_basebookdocument"),
        ("repository", "0003_alter_basebookdocument_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicedocument",
            name="catalog",
            field=models.ManyToManyField(
                blank=True, related_name="invoice", to="bookshelf.catalog"
            ),
        ),
        migrations.AlterField(
            model_name="invoicedocument",
            name="book",
            field=models.ManyToManyField(
                blank=True, related_name="invoice", to="bookshelf.book"
            ),
        ),
    ]
