# Generated by Django 4.0.2 on 2022-04-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollingstock',
            name='address',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
