# Generated by Django 4.0 on 2021-12-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cab',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cab',
            name='production_date',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cab',
            name='production_year',
            field=models.SmallIntegerField(null=True),
        ),
    ]
