# Generated by Django 4.0.2 on 2022-04-02 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_scale_manufacturer_website_and_more'),
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='RollingClass',
        ),
        migrations.AlterModelOptions(
            name='rollingclass',
            options={'ordering': ['company', 'identifier'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='rollingstock',
            options={'ordering': ['rolling_class', 'road_number'], 'verbose_name_plural': 'Rolling stock'},
        ),
        migrations.RenameField(
            model_name='rollingstock',
            old_name='epoch',
            new_name='era',
        ),
        migrations.RemoveField(
            model_name='rollingstock',
            name='_class',
        ),
        migrations.AddField(
            model_name='rollingstock',
            name='rolling_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='roster.rollingclass', verbose_name='Class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rollingstock',
            name='scale',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='metadata.scale'),
            preserve_default=False,
        ),
    ]
