# Generated by Django 4.0 on 2021-12-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_cab_notes_cab_production_date_cab_production_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cab',
            name='production_date',
        ),
        migrations.AddField(
            model_name='cab',
            name='purchase_date',
            field=models.DateField(null=True),
        ),
    ]
