# Generated by Django 4.0.2 on 2022-04-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_rename_class_rollingclass_alter_rollingclass_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollingstockimage',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
