# Generated by Django 4.0 on 2021-12-15 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_remove_cab_production_date_cab_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cab',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roster.manufacturer'),
        ),
        migrations.AlterField(
            model_name='cab',
            name='production_year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cab',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
