# Generated by Django 4.0.2 on 2022-04-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_rollingstockimage_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rollingstockimage',
            name='description',
        ),
        migrations.AddField(
            model_name='rollingclass',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
