# Generated by Django 4.0.2 on 2022-04-02 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_consistitem_consist'),
    ]

    operations = [
        migrations.AddField(
            model_name='consistitem',
            name='consist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='roster.consist'),
            preserve_default=False,
        ),
    ]
