# Generated by Django 4.0.3 on 2022-04-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_remove_rollingstockimage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollingclass',
            name='builder',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='rollingclass',
            name='wheel_arrangement',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
