# Generated by Django 4.0.2 on 2022-04-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_consistitem_consist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consistitem',
            name='consist',
        ),
        migrations.RemoveField(
            model_name='consistitem',
            name='rolling_stock',
        ),
        migrations.DeleteModel(
            name='Consist',
        ),
        migrations.DeleteModel(
            name='ConsistItem',
        ),
    ]
