# Generated by Django 4.0 on 2021-12-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_alter_cab_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cab',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
