# Generated by Django 4.0.3 on 2022-04-04 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0006_manufacturer_category'),
        ('roster', '0005_rollingclass_builder_rollingclass_wheel_arrangement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rollingclass',
            name='builder',
        ),
        migrations.AddField(
            model_name='rollingclass',
            name='manufacturer',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'real'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.manufacturer'),
        ),
        migrations.AlterField(
            model_name='rollingstock',
            name='manufacturer',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'model'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.manufacturer'),
        ),
    ]
