# Generated by Django 4.0 on 2021-12-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0006_cab_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cab',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
