# Generated by Django 4.0.3 on 2022-04-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0006_remove_rollingclass_builder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollingclass',
            name='wheel_arrangement',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
