# Generated by Django 4.0 on 2021-12-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0007_alter_cab_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cab',
            name='epoch',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
