# Generated by Django 4.0 on 2021-12-16 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0008_cab_epoch'),
    ]

    operations = [
        migrations.AddField(
            model_name='cab',
            name='decoder_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_decoder', to='roster.manufacturer'),
        ),
        migrations.AddField(
            model_name='cab',
            name='decoder_model',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='cab',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_manufacturer', to='roster.manufacturer'),
        ),
    ]
