# Generated by Django 4.0 on 2021-12-16 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0009_cab_decoder_manufacturer_cab_decoder_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cab',
            name='decoder_manufacturer',
        ),
        migrations.AlterField(
            model_name='cab',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roster.manufacturer'),
        ),
        migrations.CreateModel(
            name='Decoder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.manufacturer')),
            ],
        ),
    ]
