# Generated by Django 4.0 on 2021-12-16 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0010_remove_cab_decoder_manufacturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cab',
            name='decoder_model',
        ),
        migrations.AddField(
            model_name='cab',
            name='decoder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roster.decoder'),
        ),
    ]
