# Generated by Django 4.0 on 2021-12-16 21:26

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0011_remove_cab_decoder_model_cab_decoder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
