# Generated by Django 4.0 on 2021-12-16 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0012_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='cab',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roster.company'),
        ),
    ]
