# Generated by Django 4.0 on 2021-12-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0013_cab_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='cab',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
