# Generated by Django 4.0.1 on 2022-01-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0015_remove_decoder_manufacturer_alter_cab_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cab',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
