# Generated by Django 4.0.2 on 2022-03-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_metadata_extend'),
        ('roster', '0016_alter_cab_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cab',
            new_name='RollingStock',
        ),
    ]
