# Generated by Django 4.0.2 on 2022-03-06 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0017_rename_cab_rollingstock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rollingstock',
            options={'ordering': ['address', 'identifier'], 'verbose_name_plural': 'Rolling stock'},
        ),
    ]
