# Generated by Django 4.0.2 on 2022-03-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0006_alter_tag_options'),
        ('roster', '0018_alter_rollingstock_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollingstock',
            name='tags',
            field=models.ManyToManyField(related_name='rolling_stock', to='metadata.Tag'),
        ),
    ]
