# Generated by Django 4.0.2 on 2022-03-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0006_alter_tag_options'),
        ('roster', '0019_rollingstock_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollingstock',
            name='address',
            field=models.SmallIntegerField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name='rollingstock',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='rolling_stock', to='metadata.Tag'),
        ),
    ]
