# Generated by Django 4.0.2 on 2022-03-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0006_alter_tag_options'),
        ('roster', '0020_alter_rollingstock_address_alter_rollingstock_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollingstock',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='rolling_stock', to='metadata.Tag'),
        ),
    ]
