# Generated by Django 4.0.2 on 2022-03-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0021_alter_rollingstock_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollingstock',
            name='address',
            field=models.SmallIntegerField(blank=True, default=3, null=True),
        ),
    ]
