# Generated by Django 4.0.2 on 2022-03-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0023_image_remove_rollingstock_image_rollingstockimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollingstockimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
