# Generated by Django 4.0.2 on 2022-03-29 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0024_alter_rollingstockimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rollingstockimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='rollingstockimage',
            name='order',
        ),
    ]
