# Generated by Django 4.0.2 on 2022-03-29 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0025_alter_rollingstockimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollingStockDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='files/')),
                ('rolling_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.rollingstock')),
            ],
            options={
                'unique_together': {('rolling_stock', 'file')},
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
