# Generated by Django 4.0.2 on 2022-03-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0026_rollingstockdocument_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollingstockdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
