# Generated by Django 4.0.2 on 2022-03-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0027_alter_rollingstockdocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollingstockdocument',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
