# Generated by Django 4.0.2 on 2022-03-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0028_rollingstockdocument_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollingstock',
            name='sku',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
