# Generated by Django 4.0.2 on 2022-03-30 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0029_rollingstock_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('rollingstock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='roster.rollingstock')),
            ],
            options={
                'verbose_name_plural': 'Engines',
                'ordering': ['address', 'identifier'],
            },
            bases=('roster.rollingstock',),
        ),
    ]
