# Generated by Django 4.0.2 on 2022-03-30 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0012_alter_rollingstocktype_category'),
        ('roster', '0030_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollingstock',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.rollingstocktype'),
        ),
    ]
