# Generated by Django 4.0.2 on 2022-03-30 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0031_rollingstock_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engine',
            options={},
        ),
    ]
