# Generated by Django 4.0.2 on 2022-03-30 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0032_alter_engine_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('rollingstock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='roster.rollingstock')),
            ],
            bases=('roster.rollingstock',),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('rollingstock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='roster.rollingstock')),
            ],
            bases=('roster.rollingstock',),
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('rollingstock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='roster.rollingstock')),
            ],
            bases=('roster.rollingstock',),
        ),
    ]
