# Generated by Django 4.0.2 on 2022-03-30 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0012_alter_rollingstocktype_category'),
        ('roster', '0033_car_equipment_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rollingstock',
            name='type',
        ),
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.rollingstocktype'),
        ),
        migrations.AddField(
            model_name='engine',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.rollingstocktype'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.rollingstocktype'),
        ),
        migrations.AddField(
            model_name='other',
            name='type',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'roster.models'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.rollingstocktype'),
        ),
    ]
