# Generated by Django 4.0.3 on 2022-04-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_remove_siteconfiguration_homepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_name',
            field=models.CharField(default='Railroad Assets Manager', max_length=256),
        ),
    ]
